/*
Enter your query here.
-- */
SELECT NAME FROM STUDENTS as stud,FRIENDS,PACKAGES WHERE stud.ID=FRIENDS.ID AND FRIENDS.FRIEND_ID=PACKAGES.ID AND PACKAGES.SALARY>(SELECT SALARY FROM STUDENTS as stud2,FRIENDS as fuck,PACKAGES WHERE stud2.ID=fuck.ID AND fuck.ID=PACKAGES.ID AND fuck.ID=FRIENDS.ID) ORDER BY PACKAGES.SALARY ASC;